import { Geist, Geist_Mono } from "next/font/google";
import { Honk } from "next/font/google";
import "./globals.css";

const honk = Honk({
  variable: "--font-honk",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${honk.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
